version: "2"
services:
  api:
    image: registry.gitlab.com/applifting/productmaker/api:${IMAGE_TAG}
    build:
      context: services/api
      dockerfile: Dockerfile.api
    ports:
      - "5000:5000"
    environment:
      DEBUG: "True"
      DATABASE_URL: postgres://root@172.17.0.1:26257/productmaker
